### ISSUE TITLE
Veins receives SIGSEGV if endSimulation is used (in App init)

### ISSUE THREAD

**Issue by dbuse** [sommer/veins#194]
When the `endSimulation()` function of OMNeT++ gets called during the initialization of a `Car`'s app layer's `initialization`, the process crashes with an SIGSEGV.

An example on how to reproduce this is available here: https://github.com/sommer/veins/compare/master...dbuse:bug/sigsegv_on_endSimulation

The reason seems to be an illegal access to the `BasePhyLayer`'s `decider` field, which is a (`std::unique_ptr` to a) `nullptr` at that time.

**Comment by dbuse** [comment]
Here's some extra information on how the veins process failed:

```
env -C examples/veins ./run -d -t gdb -- -u Cmdenv 
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from opp_run_dbg...
(gdb) r
Starting program: /home/buse/src/omnetpp/5.6.2/bin/opp_run_dbg -l../../src/veins -n../../src/veins\;. --image-path=../../images -u Cmdenv
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
OMNeT++ Discrete Event Simulation  (C) 1992-2019 Andras Varga, OpenSim Ltd.
Version: 5.6.2, build: 200518-aa79d0918f, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer

Setting up Cmdenv...

Loading NED files from ../../src/veins:  41
Loading NED files from .:  1

Preparing for running configuration General, run #0...
Assigned runID=General-0-20201022-13:28:06-322812
Setting up network "RSUExampleScenario"...
Initializing...

Running simulation...
** Event #0   t=0   Elapsed: 3.9e-05s (0m 00s)  0% completed  (0% total)
     Speed:     ev/sec=0   simsec/sec=0   ev/simsec=0
     Messages:  created: 16   present: 16   in FES: 3
** Event #256   t=86.012019318318   Elapsed: 1.13756s (0m 01s)  43% completed  (43% total)
     Speed:     ev/sec=225.929   simsec/sec=75.6131   ev/simsec=2.98795
     Messages:  created: 586   present: 475   in FES: 46
** Event #6040   t=100   Elapsed: 2.19714s (0m 02s)  50% completed  (50% total)
     Speed:     ev/sec=5457.79   simsec/sec=12.2576   ev/simsec=445.258
     Messages:  created: 5146   present: 550   in FES: 5

<!> Simulation stopped with endSimulation() -- in module (veins::TraCIDemo11p) RSUExampleScenario.node[33].appl (id=212), at t=100s, event #6040

Calling finish() at end of Run #0...

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff26b2d7e in veins::BasePhyLayer::finish (this=0x5555558c4350) at veins/base/phyLayer/BasePhyLayer.cc:180
180	    decider->finish();
(gdb) bt
#0  0x00007ffff26b2d7e in veins::BasePhyLayer::finish (this=0x5555558c4350) at veins/base/phyLayer/BasePhyLayer.cc:180
#1  0x00007ffff76d1c76 in omnetpp::cModule::callFinish (this=0x5555558c4350) at cmodule.cc:1436
#2  0x00007ffff76d1c1d in omnetpp::cModule::callFinish (this=0x5555558bdff0) at cmodule.cc:1428
#3  0x00007ffff76d1c1d in omnetpp::cModule::callFinish (this=0x5555558beeb0) at cmodule.cc:1428
#4  0x00007ffff76d1c1d in omnetpp::cModule::callFinish (this=0x5555556a8ee0) at cmodule.cc:1428
#5  0x00007ffff7713806 in omnetpp::cSimulation::callFinish (this=0x5555555e7fc0) at csimulation.cc:440
#6  0x00007ffff7fbd245 in omnetpp::cmdenv::Cmdenv::doRun (this=0x5555556019d0) at cmdenv.cc:267
#7  0x00007ffff7ec3053 in omnetpp::envir::EnvirBase::run (this=0x5555556019d0) at envirbase.cc:747
#8  0x00007ffff7ebfe88 in omnetpp::envir::EnvirBase::run (this=0x5555556019d0, argc=6, argv=0x7fffffffe368, configobject=
    0x55555558d070) at envirbase.cc:358
#9  0x00007ffff7eb7170 in omnetpp::envir::setupUserInterface (argc=6, argv=0x7fffffffe368) at startup.cc:259
#10 0x00007ffff7eb81d1 in evMain (argc=6, argv=0x7fffffffe368) at evmain.cc:33
#11 0x0000555555555162 in main (argc=6, argv=0x7fffffffe368) at main.cc:31
(gdb) p decider
$1 = std::unique_ptr<veins::Decider> = {get() = 0x0}
```

My current guess is that the `BasePhyLayer::decider` field is not yet initialized. If that is all, simply wrapping Line 180 of `BasePhyLayer.cc` with a `if (decider != nullptr)` might be enough.
